config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/shop"

  resource :session
  resources :passwords, param: :token
  resource :profile, only: %i[show]

  resources :quests, only: %i[index show] do
    member do
      get :compact
      post :start
      patch :complete
    end

    resources :tasks, only: %i[show] do
      member do
        patch :complete
      end
    end
  end

  resources :monsters, only: %i[index] do
    resources :monster_rewards, only: %i[index], as: :rewards

    member do
      post :attack
    end
  end

  namespace :gm do
    resources :monsters, only: %i[new create]

    resources :quests, only: %i[new create destroy] do
      resources :tasks, only: %i[new create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/quest.rb
# == Schema Information
#
# Table name: quests
#
#  id          :integer          not null, primary key
#  description :text
#  end_at      :datetime
#  start_at    :datetime
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Quest < ApplicationRecord
  include Completable

  has_many :tasks, dependent: :destroy
  has_many :player_quests, dependent: :destroy
  has_many :players, through: :player_quests
  has_many :quest_rewards, dependent: :destroy

  after_create :randomize_rewards!

  validates :title, length: { maximum: 100 }, presence: true

  def has_started_by_some_players?
    player_quests.where(quest: self).exists?
  end

  def completed_by?(player)
    player_quests.where(player:).completed.exists?
  end

  def all_tasks_completed_by?(player)
    tasks.all? do |task|
      player.player_tasks.where(task:).completed.exists?
    end
  end

  def rewards
    quest_rewards
  end

  def randomize_rewards!
    3.times.each do
      quest_reward = self.quest_rewards.build
      quest_reward.randomize!
    end
  end
end

app/controllers/gm/quests_controller.rb
class Gm::QuestsController < QuestsController
  before_action :set_quest, only: %i[destroy]

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: "Quest was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quest.destroy!

    respond_to do |format|
      format.html { redirect_to quests_path, status: :see_other, notice: "Quest was successfully destroyed." }
    end
  end

  private
    def set_quest
      @quest = Quest.find(params.expect(:id))
    end

    def quest_params
      params.expect(quest: [ :title, :description, :completed_at, :start_at, :end_at ])
    end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_current_player, only: %i[index show start complete compact]
  before_action :set_quest, only: %i[start complete]

  def index
    @quests = Quest.limit 10
  end

  def show
    quest_id = params.expect(:id)
    @quest = Quest.includes(:tasks, { quest_rewards: :rewardable }).find(quest_id)
  end

  def start
    respond_to do |format|
      if @player.start_quest!(@quest)
        format.html { redirect_to quests_path, notice: "Quest has been started" }
      else
        format.html { redirect_to quest_path(@quest), alert: "Failed to start quest." }
      end
    end
  end

  def complete
    respond_to do |format|
      if @player.complete_quest(@quest)
        format.html { redirect_to quests_path, notice: "Quest has been completed" }
      else
        format.html { redirect_to quest_path(@quest), alert: "Failed to complete quest" }
      end
    end
  end

  def compact
    @quest = Quest.find params.expect(:id)
  end

  private

  def set_quest
    @quest = Quest.find params.expect(:id)
  end

  def set_current_player
    @player = Player.find_by(user: Current.user)
  end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_with(model: quest) do |form| %>
  <% if quest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quest.errors.count, "error") %>
        prohibited this quest from being saved:</h2>

      <ul>
        <% quest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Save quest", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/quests/_menu.html.erb
<div
  class="quest_options dropdown"
  data-controller="menu"
  data-action="click->menu#toggle"
>
  <button
    class="btn btn-sm btn-light dropdown-toggle"
    type="button"
    data-bs-toggle="dropdown"
    data-menu-target="toggle"
    aria-expanded="false"
  >
    <i class="bi bi-three-dots"></i>
  </button>
  <ul class="dropdown-menu text-center">
    <li>
      <%= link_to gm_quest_path(quest), 
        method: :delete, 
        data: { turbo_method: :delete, turbo_confirm: "Woah! Are you sure?" },
        class: "text-danger text-decoration-none" do %>
        <i class="bi bi-trash me-1"></i>
        Delete quest
      <% end %>
    </li>
  </ul>
</div>

app/views/quests/_placeholder.html.erb
<li
  class="
    quest_list_item list-group-item col-12 bg-dark border border-2 border-light
  "
>
  <div class="ms-2 me-auto">
    <div class="row gap-2">
      <div style="width: 24px; height: 24px" class="placeholder col-2 rounded-circle"></div>

      <div class="col-8 d-flex flex-column gap-2">
        <div class="placeholder w-100"></div>
        <div class="placeholder w-100"></div>
        <div class="placeholder w-25"></div>
      </div>

      <span class="placeholder col-2 rounded-pill" style="height: 20px;"></span>
    </div>
  </div>
</li>

app/views/quests/_quest.html.erb
<%= turbo_frame_tag quest do %>
  <li class="quest_list_item list-group-item ">
    <%= link_to quest_path(quest), data: { turbo_frame: "_top" } do %>
      <%= image_tag "icons/scroll_blue.png", size: "24x24", alt: "blue scroll icon" %>
      <div class="ms-2 me-auto">
        <div class="fw-semibold text-info">
          <%= quest.title %>
        </div>
        <%= quest.description %>
      </div>
      <% if !player.has_started_quest?(quest) %>
        <span class="badge text-bg-secondary rounded-pill">
          not started
        </span>
      <% elsif player.has_completed_quest?(quest) %>
        <span class="badge text-bg-success rounded-pill">
          completed
        </span>
      <% elsif player.has_started_quest?(quest) %>
        <span class="badge text-bg-warning rounded-pill">
          in-progress
        </span>
      <% end %>
    <% end %>
  </li>
<% end %>

app/views/quests/compact.html.erb
<%= render "quest", quest: @quest, player: @player %>

app/views/quests/index.html.erb
<% content_for :title, "Quests" %>
<%= render "shared/toast" %>

<article class="container">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h3 class="d-flex align-items-center gap-2">
      <%= image_tag "icons/green_flag.png", size: "32x32", alt: "green flag icon" %>
      All Quests
    </h3>

    <% if @player.is_gm? %>
      <div class="flex-shrink-0">
        <%= link_to new_gm_quest_path, class: "btn btn-primary" do %>
          <i class="bi bi-plus-lg"></i>
          Create quest
        <% end %>
      </div>
    <% end %>
  </div>

  <section class="mt-4">
    <ol class="quest_list list-group">
      <% @quests.each do |quest| %>
        <%= turbo_frame_tag quest, loading: :lazy, src: compact_quest_path(quest) do %>
          <%= render "placeholder" %>
        <% end %>
      <% end %>
    </ol>
  </section>
</article>

app/views/quests/show.html.erb
<% content_for :title, @quest.title %>
<%= render "shared/toast" %>

<article class="container mb-4">
  <div class="d-flex justify-content-between align-items-baseline mb-2">
    <h3 class="text-primary">
      <%= image_tag "icons/scroll_blue.png", size: "32x32", alt: "scroll icon" %>
      <u>
        Quest #<%= @quest.id %>
      </u>
    </h3>

    <% if @player.is_gm? %>
      <%= render "menu", quest: @quest %>
    <% end %>
  </div>

  <div class="mb-4">
    <% if @quest.has_ended? %>
      <p class="text-danger">Quest has endend
        <%= time_ago_in_words(@quest.end_at) %>
        ago</p>
    <% elsif !@quest.endless? %>
      <p class="text-warning">Quest end in
        <%= distance_of_time_in_words(Time.now, @quest.end_at) %></p>
    <% end %>
  </div>

  <h4 class="fs-5 mb-0 text-primary">
    <%= @quest.title %>
  </h4>

  <p class="mb-4 fs-6"><%= @quest.description %></p>

  <section>
    <%= render "tasks/task_list", tasks: @quest.tasks, player: @player %>
  </section>
</article>

<div class="d-flex justify-content-end">
  <% if @player.is_gm? && !@quest.has_started_by_some_players? %>
    <%= link_to "Add Tasks", new_gm_quest_task_path(@quest) %>
  <% end %>
</div>

<article class="container">
  <h5 class="mb-4">Quest rewards</h5>

  <section class="row">
    <%= render "shared/game/rewards", rewards: @quest.rewards %>
  </section>
</article>

<div class="d-flex justify-content-end mt-4">
  <% if @player.has_started_quest?(@quest) %>
    <%= button_to "Complete Quest",
    complete_quest_path(@quest),
    method: :patch,
    class: "btn btn-primary",
    disabled: !@player.can_complete_quest?(@quest) %>
  <% else %>
    <%= button_to "Start Quest",
    start_quest_path(@quest),
    method: :post,
    class: "btn btn-primary",
    disabled: @quest.has_ended? %>
  <% end %>
</div>