config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/shop"

  resource :session
  resources :passwords, param: :token
  resource :profile, only: %i[show]

  resources :quests, only: %i[index show] do
    member do
      get :compact
      post :start
      patch :complete
    end

    resources :tasks, only: %i[show] do
      member do
        patch :complete
      end
    end
  end

  resources :monsters, only: %i[index] do
    resources :monster_rewards, only: %i[index], as: :rewards

    member do
      post :attack
    end
  end

  namespace :gm do
    resources :monsters, only: %i[new create]

    resources :quests, only: %i[new create destroy] do
      resources :tasks, only: %i[new create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/monster.rb
# == Schema Information
#
# Table name: monsters
#
#  id          :integer          not null, primary key
#  asset_key   :string
#  atk         :integer
#  def         :integer
#  description :string
#  hp          :integer
#  level       :integer          not null
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  player_id   :integer          not null
#
# Indexes
#
#  index_monsters_on_player_id  (player_id)
#
# Foreign Keys
#
#  player_id  (player_id => players.id)
#
class Monster < ApplicationRecord
  include Rewardable, Spawnable

  belongs_to :defeater, class_name: "Player", foreign_key: "player_id", optional: true

  validates :title, length: { maximum: 100 }, presence: true
  validates :hp, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :atk, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :def, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :level, presence: true, numericality: { greater_than: 0, lesser_than_or_equal_to: 64 }

  scope :defeated, -> { where.not(defeater: nil) }
  scope :undefeated, -> { where(defeater: nil) }

  def lesser_tier? = (1..20).include? level
  def champion_tier? = (21..40).include? level
  def boss_tier? = (41..64).include? level

  def defeated_by(player)
    transaction do
      self.defeater = player
      self.save!

      player.receive_rewards_from self
    end
  end

  def take_damage(damage)
    if self.hp < damage
      self.hp = 0
    else
      self.hp -= damage
    end

    self.save!
  end

  def is_dead? = hp == 0

  def image_path = "mons/#{asset_key}.png"

  def original_stats
    monsters_data.find { _1["level"] == self.level }
  end

  def monsters_data
    data_path = Rails.root.join "app", "assets", "data", "monsters.json"
    data = File.read data_path
    JSON.parse data
  end
end

app/models/monster/rewardable.rb
module Monster::Rewardable
  extend ActiveSupport::Concern

  included do
    has_many :monster_rewards, dependent: :destroy
    after_create :randomize_rewards!
  end

  def rewards = monster_rewards

  private

  def randomize_rewards!
    3.times.each do
      reward_type = randomize_reward_type.to_s.constantize
      reward = reward_type.randomize!
      monster_rewards.create! rewardable: reward
    end
  end

  def randomize_reward_type
    rewards = %i[Gear GoldReward ExpReward]
    weights = [ 35, 35, 30 ]
    cumulative = 0
    random = rand weights.sum

    weights.each_with_index do |weight, idx|
      cumulative += weight
      return rewards[idx] if cumulative >= random
    end
  end
end

app/models/monster/spawnable.rb
module Monster::Spawnable
  extend ActiveSupport::Concern

  included do
    validate :validate_can_spawn, on: :create
  end

  class_methods do
    def can_spawn? = Monster.defeated.count == Monster.count
  end

  def spawn!(level = randomize_monster_level)
    monster = monsters_data.find { _1["level"] == level }
    Monster.create! monster
  end


  def validate_can_spawn
    errors.add(:monster, "cannot spawn new monster when some monsters still alive") unless Monster.can_spawn?
  end

  private

  def randomize_monster_tier
    monster_tiers = %i[lesser champion boss]
    weights = [ 85, 10, 5 ]
    cumulative = 0
    random = rand weights.sum

    weights.each_with_index do |weight, idx|
      cumulative += weight
      return monster_tiers[idx] if cumulative >= random
    end
  end

  def randomize_monster_level
    tier = randomize_monster_tier
    rand level_range_from(tier)
  end

  def level_range_from(tier)
    case tier
    when :lesser
      1..20
    when :champion
      21..40
    else
      41..64
    end
  end
end

app/controllers/gm/monsters_controller.rb
class Gm::MonstersController < ApplicationController
  # TODO: Handle access to gm routes
  def show
    @player = Player.find_by(user: Current.user)
    @monster = Monster.includes(monster_rewards: :rewardable).undefeated.first
  end

  def create
    @monster = Monster.new.spawn!

    if @monster.errors.empty?
      redirect_to monsters_path, notice: "Boss: #{@monster.title} has been spawned!"
    else
      render monsters_path, status: :unprocessable_entity
    end
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_player
  before_action :ensure_boss_spawned?, only: %i[attack]

  def index
    @monster = Monster.undefeated.first
  end

  def attack
    @monster ||= Monster.find_by(id: params.expect(:id))

    respond_to do |format|
      @player.attack(@monster)

      if @monster.is_dead?
        @monster.defeated_by @player
        format.html { redirect_to monster_rewards_path(@monster), notice: "Boss: #{@monster.title} is defeated!" }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("boss_hp",
            partial: "monsters/boss_hp",
            locals: { monster: @monster }
          )
        end
      end
    end
  end

  private

  def set_player
    @player = Player.find_by user: Current.user
  end

  def ensure_boss_spawned?
    @monster = Monster.find_by(id: params.expect(:id))
    render monsters_path, status: :unprocessable_entity if @monster.nil?
  end
end

app/views/monsters/_boss.html.erb
<div id="boss_hp" class="d-flex flex-column align-items-end w-100 mb-4">
  <%= render "monsters/boss_hp", monster: monster %>
</div>

<div class="text-end">
  <%= image_tag monster.image_path,
  class: "pixelated monster_image",
  size: "144x144",
  alt: "monster image",
  data: {
    action: "animationend->battle#takeDamageDone",
    battle_target: "monster",
  } %>
</div>

app/views/monsters/_boss_hp.html.erb
<% original_hp = monster.original_stats["hp"] %>
<% hp_percentage = ((100.0 / original_hp.to_f) * monster.hp.to_f).round 2 %>

<div class="d-flex align-items-center gap-2">
  <%= image_tag "icons/heart.png", class: "pixelated", size: "24x24", alt: "hear icon" %>
  <span class="fs-2">
    <b>HP:</b>
    <%= "#{monster.hp}/#{original_hp}" %>
  </span>
</div>

<div class="w-50">
  <div
    class="progress"
    role="progressbar"
    aria-label="hp bar"
    aria-valuenow="<%= monster.hp %>"
    aria-valuemin="0"
    aria-valuemax="100"
  >
    <%= content_tag :div, class: ["progress-bar", { "bg-success": hp_percentage > 50, "bg-warning": hp_percentage <= 50 }], style: "width: #{hp_percentage}%;" do %>
    <% end %>
  </div>
</div>

app/views/monsters/index.html.erb
<% content_for :title, "Raid Boss" %>
<%= render "shared/toast" %>

<article
  class="container d-flex align-items-center flex-column h-100"
  data-controller="battle"
  data-battle-mons-attacked-class="monster_image--attacked"
  data-battle-hero-attack-class="hero_image--attack"
>
  <h3 class="d-flex align-items-center text-danger mb-0">
    <%= image_tag "icons/boss.png", class: "pixelated", size: "64x64", alt: "boss icon" %>
    <% if @monster.present? %>
      <%= @monster.title %>
    <% else %>
      Wanna raid Boss?
    <% end %>
  </h3>

  <section class="mt-5 w-100 text-center">
    <% if @monster.present? %>
      <%= render "monsters/boss", monster: @monster %>

    <% else %>
      <% if @player.is_gm? && Monster.can_spawn? %>
        <%= button_to "Spawn Monster",
        gm_monsters_path,
        method: :post,
        class: "btn btn-lg btn-primary" %>
      <% else %>
        <p>
          No monster to fight yet.
        </p>
      <% end %>
    <% end %>
  </section>

  <% if @monster.present? %>
    <section class="mt-5 w-100">
      <div class="d-flex justify-content-between">
        <div class="flex-grow-1">
          <%= render "shared/game/hero", player: @player %>
        </div>

        <%= button_to attack_monster_path(@monster), 
          method: :post, 
          class: "atk-btn rounded-circle", 
          form_class: "align-self-center",
          data: { battle_target: "atkButton", action: "click->battle#attack" } do %>
          <div class="d-flex">
            <%= image_tag "icons/sword_atk.png",
            class: "pixelated m-auto",
            size: "64x64",
            alt: "sword attack icon" %>
          </div>
        <% end %>
      </div>
    </section>
  <% end %>
</article>