config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/shop"

  resource :session
  resources :passwords, param: :token
  resource :profile, only: %i[show]

  resources :quests, only: %i[index show] do
    member do
      get :compact
      post :start
      patch :complete
    end

    resources :tasks, only: %i[show] do
      member do
        patch :complete
      end
    end
  end

  resources :monsters, only: %i[index] do
    resources :monster_rewards, only: %i[index], as: :rewards

    member do
      post :attack
    end
  end

  namespace :gm do
    resources :monsters, only: %i[new create]

    resources :quests, only: %i[new create destroy] do
      resources :tasks, only: %i[new create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :text
#  end_at      :datetime
#  start_at    :datetime
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  quest_id    :integer          not null
#
# Indexes
#
#  index_tasks_on_quest_id  (quest_id)
#
# Foreign Keys
#
#  quest_id  (quest_id => quests.id)
#
class Task < ApplicationRecord
  include Completable

  belongs_to :quest
  has_many :player_tasks, dependent: :destroy

  validate :quest_not_started_by_some_players

  def completed_by?(player)
    player_tasks.where(player:).where.not(completed_at: nil).exists?
  end

  private

  def quest_not_started_by_some_players
    if quest.has_started_by_some_players?
      errors.add(:task, "cannot create task for on-going quest")
    end
  end
end

app/controllers/gm/tasks_controller.rb
class Gm::TasksController < ApplicationController
  before_action :set_quest, only: %i[ new create ]

  def new
  end

  def create
    @quest.tasks.build task_params

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: "Create quest task successfully." }
      else
        format.html { render new_gm_quest_task_path(@quest), status: :unprocessable_entity, alert: "Failed to create quest task." }
      end
    end
  end

  private

  def set_quest
    @quest = Quest.find(params.expect(:quest_id))
  end

  def task_params
    params.expect(task: [ :title, :description, :start_at, :end_at ])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_current_player
  before_action :set_task

  def show
  end

  def complete
    respond_to do |format|
      if @player.complete_task(@task)
        format.html { redirect_to quest_path(@task.quest), notice: "Task has been completed" }
      else
        format.html { redirect_to quest_path(@task.quest), alert: "Failed to complete task." }
      end
    end
  end

  private

  def set_task
    @task = Task.find params.expect(:id)
  end

  def set_current_player
    @player = Player.find_by(user: Current.user)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_list.html.erb
<ol class="task_list list-group">
  <% tasks.each do |task| %>
    <li class="task_list_item list-group-item">
      <%= link_to quest_task_path(task.quest_id, task.id), data: { turbo_frame: "task_detail" } do %>
        <%= image_tag "icons/task_scroll.png", size: "24x24", alt: "task scroll icon" %>
        <div class="ms-2 me-auto">
          <div class="fw-semibold text-info">
            <%= task.title %>
          </div>
          <%= task.description %>
        </div>
        <% if @player.has_completed_task? task %>
          <span class="badge text-bg-success rounded-pill">
            completed
          </span>
        <% elsif !@player.has_started_quest? task.quest %>
          <span class="badge text-bg-secondary rounded-pill">
            not started
          </span>
        <% else %>
          <span class="badge text-bg-warning rounded-pill">
            in-progress
          </span>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ol>

<div
  class="modal"
  tabindex="-1"
  data-controller="modal"
  data-action="turbo:frame-load->modal#show"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark">Task details</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <%= turbo_frame_tag "task_detail" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<% content_for :title, "Task #{@task.id}" %>
<%= render "shared/toast" %>

<%= turbo_frame_tag "task_detail" do %>
  <article class="container">
    <h6 class="d-flex align-items-center gap-2 text-light">
      <%= image_tag "icons/task_scroll.png",
      class: "align-self-baseline",
      size: "24x24",
      alt: "task scroll icon" %>
      <%= @task.title %>
    </h6>

    <section>
      <p class="text-dark"><%= @task.description %></p>

      <% if @player.has_started_quest?(@task.quest) %>
        <%= button_to "Complete Task",
        complete_quest_task_path(@task.quest, @task),
        method: :patch,
        class: "btn btn-primary",
        disabled: @player.has_completed_task?(@task),
        data: {
          turbo_frame: "_top",
        } %>
      <% end %>

      <% if @player.has_completed_task? @task %>
        <p class="text-success">Completed
          <%= time_ago_in_words(@player.completed_task_at @task) %>
          ago
        </p>
      <% end %>
    </section>
  </article>
<% end %>