config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/shop"

  resource :session
  resources :passwords, param: :token
  resource :profile, only: %i[show]

  resources :quests, only: %i[index show] do
    member do
      get :compact
      post :start
      patch :complete
    end

    resources :tasks, only: %i[show] do
      member do
        patch :complete
      end
    end
  end

  resources :monsters, only: %i[index] do
    resources :monster_rewards, only: %i[index], as: :rewards

    member do
      post :attack
    end
  end

  namespace :gm do
    resources :monsters, only: %i[new create]

    resources :quests, only: %i[new create destroy] do
      resources :tasks, only: %i[new create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_dock.html.erb
<div class="dock">
  <ul class="dock_items">
    <li>
      <%= link_to root_path, class: "dock_item" do %>
        <%= image_tag "icons/tent.png", class: "pixelated", size: "24x24", alt: "home icon" %>
        Home
      <% end %>
    </li>
    <li>
      <%= link_to quests_path, class: "dock_item" do %>
        <%= image_tag "icons/scroll_blue.png",
        class: "pixelated",
        size: "24x24",
        alt: "scroll icon" %>
        Quest
      <% end %>
    </li>
    <li>
      <%= link_to monsters_path, class: "dock_item" do %>
        <%= image_tag "icons/dungeon_portal.png",
        class: "pixelated",
        size: "24x24",
        alt: "dungeon portal icon" %>
        Dungeon
      <% end %>
    </li>
    <li>
      <%= link_to pages_shop_path, class: "dock_item" do %>
        <%= image_tag "icons/treasure.png",
        class: "pixelated",
        size: "24x24",
        alt: "trasure icon" %>
        Shop
      <% end %>
    </li>
    <li>
      <%= link_to profile_path, class: "dock_item" do %>
        <%= image_tag "icons/armor.png",
        class: "pixelated",
        size: "24x24",
        alt: "armor icon" %>
        Player
      <% end %>
    </li>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Habite" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-refresh-method" content="morph">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
      href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap"
      rel="stylesheet"
    >
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.13.1/font/bootstrap-icons.min.css" %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class=" main_layout container pt-4 px-3 ">
      <%= yield %>
    </main>
    <% unless Current.user.nil? %>
      <%= render "layouts/dock" %>
    <% end %>
  </body>
</html>